/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public class ObjConshdlr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ObjConshdlr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjConshdlr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SCIPJNIJNI.delete_ObjConshdlr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    SCIPJNIJNI.ObjConshdlr_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    SCIPJNIJNI.ObjConshdlr_change_ownership(this, swigCPtr, true);
  }

  public void setScip_(SWIGTYPE_p_SCIP value) {
    SCIPJNIJNI.ObjConshdlr_scip__set(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(value));
  }

  public SWIGTYPE_p_SCIP getScip_() {
    long cPtr = SCIPJNIJNI.ObjConshdlr_scip__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SCIP(cPtr, false);
  }

  public void setScip_name_(String value) {
    SCIPJNIJNI.ObjConshdlr_scip_name__set(swigCPtr, this, value);
  }

  public String getScip_name_() {
    return SCIPJNIJNI.ObjConshdlr_scip_name__get(swigCPtr, this);
  }

  public void setScip_desc_(String value) {
    SCIPJNIJNI.ObjConshdlr_scip_desc__set(swigCPtr, this, value);
  }

  public String getScip_desc_() {
    return SCIPJNIJNI.ObjConshdlr_scip_desc__get(swigCPtr, this);
  }

  public int getScip_sepapriority_() {
    return SCIPJNIJNI.ObjConshdlr_scip_sepapriority__get(swigCPtr, this);
  }

  public int getScip_enfopriority_() {
    return SCIPJNIJNI.ObjConshdlr_scip_enfopriority__get(swigCPtr, this);
  }

  public int getScip_checkpriority_() {
    return SCIPJNIJNI.ObjConshdlr_scip_checkpriority__get(swigCPtr, this);
  }

  public int getScip_sepafreq_() {
    return SCIPJNIJNI.ObjConshdlr_scip_sepafreq__get(swigCPtr, this);
  }

  public int getScip_propfreq_() {
    return SCIPJNIJNI.ObjConshdlr_scip_propfreq__get(swigCPtr, this);
  }

  public int getScip_eagerfreq_() {
    return SCIPJNIJNI.ObjConshdlr_scip_eagerfreq__get(swigCPtr, this);
  }

  public int getScip_maxprerounds_() {
    return SCIPJNIJNI.ObjConshdlr_scip_maxprerounds__get(swigCPtr, this);
  }

  public long getScip_delaysepa_() {
    return SCIPJNIJNI.ObjConshdlr_scip_delaysepa__get(swigCPtr, this);
  }

  public long getScip_delayprop_() {
    return SCIPJNIJNI.ObjConshdlr_scip_delayprop__get(swigCPtr, this);
  }

  public long getScip_needscons_() {
    return SCIPJNIJNI.ObjConshdlr_scip_needscons__get(swigCPtr, this);
  }

  public long getScip_proptiming_() {
    return SCIPJNIJNI.ObjConshdlr_scip_proptiming__get(swigCPtr, this);
  }

  public long getScip_presoltiming_() {
    return SCIPJNIJNI.ObjConshdlr_scip_presoltiming__get(swigCPtr, this);
  }

  public ObjConshdlr(SWIGTYPE_p_SCIP scip, String name, String desc, int sepapriority, int enfopriority, int checkpriority, int sepafreq, int propfreq, int eagerfreq, int scip_maxprerounds, long delaysepa, long delayprop, long needscons, long proptiming, long presoltiming) {
    this(SCIPJNIJNI.new_ObjConshdlr(SWIGTYPE_p_SCIP.getCPtr(scip), name, desc, sepapriority, enfopriority, checkpriority, sepafreq, propfreq, eagerfreq, scip_maxprerounds, delaysepa, delayprop, needscons, proptiming, presoltiming), true);
    SCIPJNIJNI.ObjConshdlr_director_connect(this, swigCPtr, true, true);
  }

  public SCIP_Retcode scip_free(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_free(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr)) : SCIPJNIJNI.ObjConshdlr_scip_freeSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr)));
  }

  public SCIP_Retcode scip_init(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_init(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss) : SCIPJNIJNI.ObjConshdlr_scip_initSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss));
  }

  public SCIP_Retcode scip_exit(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_exit(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss) : SCIPJNIJNI.ObjConshdlr_scip_exitSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss));
  }

  public SCIP_Retcode scip_initpre(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_initpre(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss) : SCIPJNIJNI.ObjConshdlr_scip_initpreSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss));
  }

  public SCIP_Retcode scip_exitpre(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_exitpre(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss) : SCIPJNIJNI.ObjConshdlr_scip_exitpreSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss));
  }

  public SCIP_Retcode scip_initsol(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_initsol(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss) : SCIPJNIJNI.ObjConshdlr_scip_initsolSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss));
  }

  public SCIP_Retcode scip_exitsol(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss, long restart) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_exitsol(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, restart) : SCIPJNIJNI.ObjConshdlr_scip_exitsolSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, restart));
  }

  public SCIP_Retcode scip_delete(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons, SWIGTYPE_p_p_SCIP_CONSDATA consdata) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_delete(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_p_SCIP_CONSDATA.getCPtr(consdata)) : SCIPJNIJNI.ObjConshdlr_scip_deleteSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_p_SCIP_CONSDATA.getCPtr(consdata)));
  }

  public SCIP_Retcode scip_trans(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS sourcecons, SWIGTYPE_p_p_SCIP_CONS targetcons) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_trans(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(sourcecons), SWIGTYPE_p_p_SCIP_CONS.getCPtr(targetcons)) : SCIPJNIJNI.ObjConshdlr_scip_transSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(sourcecons), SWIGTYPE_p_p_SCIP_CONS.getCPtr(targetcons)));
  }

  public SCIP_Retcode scip_initlp(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss, SWIGTYPE_p_unsigned_int infeasible) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_initlp(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, SWIGTYPE_p_unsigned_int.getCPtr(infeasible)) : SCIPJNIJNI.ObjConshdlr_scip_initlpSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, SWIGTYPE_p_unsigned_int.getCPtr(infeasible)));
  }

  public SCIP_Retcode scip_sepalp(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss, int nusefulconss, SWIGTYPE_p_SCIP_Result result) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_sepalp(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, SWIGTYPE_p_SCIP_Result.getCPtr(result)) : SCIPJNIJNI.ObjConshdlr_scip_sepalpSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, SWIGTYPE_p_SCIP_Result.getCPtr(result)));
  }

  public SCIP_Retcode scip_sepasol(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss, int nusefulconss, SWIGTYPE_p_SCIP_SOL sol, SWIGTYPE_p_SCIP_Result result) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_sepasol(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, SWIGTYPE_p_SCIP_SOL.getCPtr(sol), SWIGTYPE_p_SCIP_Result.getCPtr(result)) : SCIPJNIJNI.ObjConshdlr_scip_sepasolSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, SWIGTYPE_p_SCIP_SOL.getCPtr(sol), SWIGTYPE_p_SCIP_Result.getCPtr(result)));
  }

  public SCIP_Retcode scip_enfolp(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss, int nusefulconss, long solinfeasible, SWIGTYPE_p_SCIP_Result result) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_enfolp(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, solinfeasible, SWIGTYPE_p_SCIP_Result.getCPtr(result)) : SCIPJNIJNI.ObjConshdlr_scip_enfolpSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, solinfeasible, SWIGTYPE_p_SCIP_Result.getCPtr(result)));
  }

  public SCIP_Retcode scip_enforelax(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_SOL sol, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss, int nusefulconss, long solinfeasible, SWIGTYPE_p_SCIP_Result result) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_enforelax(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_SOL.getCPtr(sol), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, solinfeasible, SWIGTYPE_p_SCIP_Result.getCPtr(result)) : SCIPJNIJNI.ObjConshdlr_scip_enforelaxSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_SOL.getCPtr(sol), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, solinfeasible, SWIGTYPE_p_SCIP_Result.getCPtr(result)));
  }

  public SCIP_Retcode scip_enfops(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss, int nusefulconss, long solinfeasible, long objinfeasible, SWIGTYPE_p_SCIP_Result result) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_enfops(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, solinfeasible, objinfeasible, SWIGTYPE_p_SCIP_Result.getCPtr(result)) : SCIPJNIJNI.ObjConshdlr_scip_enfopsSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, solinfeasible, objinfeasible, SWIGTYPE_p_SCIP_Result.getCPtr(result)));
  }

  public SCIP_Retcode scip_check(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss, SWIGTYPE_p_SCIP_SOL sol, long checkintegrality, long checklprows, long printreason, long completely, SWIGTYPE_p_SCIP_Result result) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_check(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, SWIGTYPE_p_SCIP_SOL.getCPtr(sol), checkintegrality, checklprows, printreason, completely, SWIGTYPE_p_SCIP_Result.getCPtr(result)) : SCIPJNIJNI.ObjConshdlr_scip_checkSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, SWIGTYPE_p_SCIP_SOL.getCPtr(sol), checkintegrality, checklprows, printreason, completely, SWIGTYPE_p_SCIP_Result.getCPtr(result)));
  }

  public SCIP_Retcode scip_prop(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss, int nusefulconss, int nmarkedconss, SWIGTYPE_p_SCIP_PROPTIMING proptiming, SWIGTYPE_p_SCIP_Result result) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_prop(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, nmarkedconss, SWIGTYPE_p_SCIP_PROPTIMING.getCPtr(proptiming), SWIGTYPE_p_SCIP_Result.getCPtr(result)) : SCIPJNIJNI.ObjConshdlr_scip_propSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nusefulconss, nmarkedconss, SWIGTYPE_p_SCIP_PROPTIMING.getCPtr(proptiming), SWIGTYPE_p_SCIP_Result.getCPtr(result)));
  }

  public SCIP_Retcode scip_presol(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss, int nrounds, SWIGTYPE_p_SCIP_PRESOLTIMING presoltiming, int nnewfixedvars, int nnewaggrvars, int nnewchgvartypes, int nnewchgbds, int nnewholes, int nnewdelconss, int nnewaddconss, int nnewupgdconss, int nnewchgcoefs, int nnewchgsides, SWIGTYPE_p_int nfixedvars, SWIGTYPE_p_int naggrvars, SWIGTYPE_p_int nchgvartypes, SWIGTYPE_p_int nchgbds, SWIGTYPE_p_int naddholes, SWIGTYPE_p_int ndelconss, SWIGTYPE_p_int naddconss, SWIGTYPE_p_int nupgdconss, SWIGTYPE_p_int nchgcoefs, SWIGTYPE_p_int nchgsides, SWIGTYPE_p_SCIP_Result result) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_presol(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nrounds, SWIGTYPE_p_SCIP_PRESOLTIMING.getCPtr(presoltiming), nnewfixedvars, nnewaggrvars, nnewchgvartypes, nnewchgbds, nnewholes, nnewdelconss, nnewaddconss, nnewupgdconss, nnewchgcoefs, nnewchgsides, SWIGTYPE_p_int.getCPtr(nfixedvars), SWIGTYPE_p_int.getCPtr(naggrvars), SWIGTYPE_p_int.getCPtr(nchgvartypes), SWIGTYPE_p_int.getCPtr(nchgbds), SWIGTYPE_p_int.getCPtr(naddholes), SWIGTYPE_p_int.getCPtr(ndelconss), SWIGTYPE_p_int.getCPtr(naddconss), SWIGTYPE_p_int.getCPtr(nupgdconss), SWIGTYPE_p_int.getCPtr(nchgcoefs), SWIGTYPE_p_int.getCPtr(nchgsides), SWIGTYPE_p_SCIP_Result.getCPtr(result)) : SCIPJNIJNI.ObjConshdlr_scip_presolSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss, nrounds, SWIGTYPE_p_SCIP_PRESOLTIMING.getCPtr(presoltiming), nnewfixedvars, nnewaggrvars, nnewchgvartypes, nnewchgbds, nnewholes, nnewdelconss, nnewaddconss, nnewupgdconss, nnewchgcoefs, nnewchgsides, SWIGTYPE_p_int.getCPtr(nfixedvars), SWIGTYPE_p_int.getCPtr(naggrvars), SWIGTYPE_p_int.getCPtr(nchgvartypes), SWIGTYPE_p_int.getCPtr(nchgbds), SWIGTYPE_p_int.getCPtr(naddholes), SWIGTYPE_p_int.getCPtr(ndelconss), SWIGTYPE_p_int.getCPtr(naddconss), SWIGTYPE_p_int.getCPtr(nupgdconss), SWIGTYPE_p_int.getCPtr(nchgcoefs), SWIGTYPE_p_int.getCPtr(nchgsides), SWIGTYPE_p_SCIP_Result.getCPtr(result)));
  }

  public SCIP_Retcode scip_resprop(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons, SWIGTYPE_p_SCIP_VAR infervar, int inferinfo, SCIP_BoundType boundtype, SWIGTYPE_p_SCIP_BDCHGIDX bdchgidx, double relaxedbd, SWIGTYPE_p_SCIP_Result result) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_resprop(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_SCIP_VAR.getCPtr(infervar), inferinfo, boundtype.swigValue(), SWIGTYPE_p_SCIP_BDCHGIDX.getCPtr(bdchgidx), relaxedbd, SWIGTYPE_p_SCIP_Result.getCPtr(result)) : SCIPJNIJNI.ObjConshdlr_scip_respropSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_SCIP_VAR.getCPtr(infervar), inferinfo, boundtype.swigValue(), SWIGTYPE_p_SCIP_BDCHGIDX.getCPtr(bdchgidx), relaxedbd, SWIGTYPE_p_SCIP_Result.getCPtr(result)));
  }

  public SCIP_Retcode scip_lock(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons, SWIGTYPE_p_SCIP_LOCKTYPE locktype, int nlockspos, int nlocksneg) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_lock(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_SCIP_LOCKTYPE.getCPtr(locktype), nlockspos, nlocksneg) : SCIPJNIJNI.ObjConshdlr_scip_lockSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_SCIP_LOCKTYPE.getCPtr(locktype), nlockspos, nlocksneg));
  }

  public SCIP_Retcode scip_active(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_active(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons)) : SCIPJNIJNI.ObjConshdlr_scip_activeSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons)));
  }

  public SCIP_Retcode scip_deactive(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_deactive(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons)) : SCIPJNIJNI.ObjConshdlr_scip_deactiveSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons)));
  }

  public SCIP_Retcode scip_enable(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_enable(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons)) : SCIPJNIJNI.ObjConshdlr_scip_enableSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons)));
  }

  public SCIP_Retcode scip_disable(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_disable(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons)) : SCIPJNIJNI.ObjConshdlr_scip_disableSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons)));
  }

  public SCIP_Retcode scip_delvars(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS conss, int nconss) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_delvars(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss) : SCIPJNIJNI.ObjConshdlr_scip_delvarsSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(conss), nconss));
  }

  public SCIP_Retcode scip_print(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons, SWIGTYPE_p_FILE file) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_print(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_FILE.getCPtr(file)) : SCIPJNIJNI.ObjConshdlr_scip_printSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_FILE.getCPtr(file)));
  }

  public SCIP_Retcode scip_copy(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_p_SCIP_CONS cons, String name, SWIGTYPE_p_SCIP sourcescip, SWIGTYPE_p_SCIP_CONSHDLR sourceconshdlr, SWIGTYPE_p_SCIP_CONS sourcecons, SWIGTYPE_p_SCIP_HASHMAP varmap, SWIGTYPE_p_SCIP_HASHMAP consmap, long initial, long separate, long enforce, long check, long propagate, long local, long modifiable, long dynamic, long removable, long stickingatnode, long global, SWIGTYPE_p_unsigned_int valid) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_copy(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_p_SCIP_CONS.getCPtr(cons), name, SWIGTYPE_p_SCIP.getCPtr(sourcescip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(sourceconshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(sourcecons), SWIGTYPE_p_SCIP_HASHMAP.getCPtr(varmap), SWIGTYPE_p_SCIP_HASHMAP.getCPtr(consmap), initial, separate, enforce, check, propagate, local, modifiable, dynamic, removable, stickingatnode, global, SWIGTYPE_p_unsigned_int.getCPtr(valid)) : SCIPJNIJNI.ObjConshdlr_scip_copySwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_p_SCIP_CONS.getCPtr(cons), name, SWIGTYPE_p_SCIP.getCPtr(sourcescip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(sourceconshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(sourcecons), SWIGTYPE_p_SCIP_HASHMAP.getCPtr(varmap), SWIGTYPE_p_SCIP_HASHMAP.getCPtr(consmap), initial, separate, enforce, check, propagate, local, modifiable, dynamic, removable, stickingatnode, global, SWIGTYPE_p_unsigned_int.getCPtr(valid)));
  }

  public SCIP_Retcode scip_parse(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_p_SCIP_CONS cons, String name, String str, long initial, long separate, long enforce, long check, long propagate, long local, long modifiable, long dynamic, long removable, long stickingatnode, SWIGTYPE_p_unsigned_int success) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_parse(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(cons), name, str, initial, separate, enforce, check, propagate, local, modifiable, dynamic, removable, stickingatnode, SWIGTYPE_p_unsigned_int.getCPtr(success)) : SCIPJNIJNI.ObjConshdlr_scip_parseSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_p_SCIP_CONS.getCPtr(cons), name, str, initial, separate, enforce, check, propagate, local, modifiable, dynamic, removable, stickingatnode, SWIGTYPE_p_unsigned_int.getCPtr(success)));
  }

  public SCIP_Retcode scip_getvars(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons, SWIGTYPE_p_p_SCIP_VAR vars, int varssize, SWIGTYPE_p_unsigned_int success) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_getvars(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_p_SCIP_VAR.getCPtr(vars), varssize, SWIGTYPE_p_unsigned_int.getCPtr(success)) : SCIPJNIJNI.ObjConshdlr_scip_getvarsSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_p_SCIP_VAR.getCPtr(vars), varssize, SWIGTYPE_p_unsigned_int.getCPtr(success)));
  }

  public SCIP_Retcode scip_getnvars(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons, SWIGTYPE_p_int nvars, SWIGTYPE_p_unsigned_int success) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_getnvars(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_int.getCPtr(nvars), SWIGTYPE_p_unsigned_int.getCPtr(success)) : SCIPJNIJNI.ObjConshdlr_scip_getnvarsSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_int.getCPtr(nvars), SWIGTYPE_p_unsigned_int.getCPtr(success)));
  }

  public SCIP_Retcode scip_getdivebdchgs(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_DIVESET diveset, SWIGTYPE_p_SCIP_SOL sol, SWIGTYPE_p_unsigned_int success, SWIGTYPE_p_unsigned_int infeasible) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_getdivebdchgs(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_DIVESET.getCPtr(diveset), SWIGTYPE_p_SCIP_SOL.getCPtr(sol), SWIGTYPE_p_unsigned_int.getCPtr(success), SWIGTYPE_p_unsigned_int.getCPtr(infeasible)) : SCIPJNIJNI.ObjConshdlr_scip_getdivebdchgsSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_DIVESET.getCPtr(diveset), SWIGTYPE_p_SCIP_SOL.getCPtr(sol), SWIGTYPE_p_unsigned_int.getCPtr(success), SWIGTYPE_p_unsigned_int.getCPtr(infeasible)));
  }

  public SCIP_Retcode scip_getpermsymgraph(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons, SWIGTYPE_p_SYM_GRAPH graph, SWIGTYPE_p_unsigned_int success) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_getpermsymgraph(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_SYM_GRAPH.getCPtr(graph), SWIGTYPE_p_unsigned_int.getCPtr(success)) : SCIPJNIJNI.ObjConshdlr_scip_getpermsymgraphSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_SYM_GRAPH.getCPtr(graph), SWIGTYPE_p_unsigned_int.getCPtr(success)));
  }

  public SCIP_Retcode scip_getsignedpermsymgraph(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_CONSHDLR conshdlr, SWIGTYPE_p_SCIP_CONS cons, SWIGTYPE_p_SYM_GRAPH graph, SWIGTYPE_p_unsigned_int success) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjConshdlr.class) ? SCIPJNIJNI.ObjConshdlr_scip_getsignedpermsymgraph(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_SYM_GRAPH.getCPtr(graph), SWIGTYPE_p_unsigned_int.getCPtr(success)) : SCIPJNIJNI.ObjConshdlr_scip_getsignedpermsymgraphSwigExplicitObjConshdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_CONSHDLR.getCPtr(conshdlr), SWIGTYPE_p_SCIP_CONS.getCPtr(cons), SWIGTYPE_p_SYM_GRAPH.getCPtr(graph), SWIGTYPE_p_unsigned_int.getCPtr(success)));
  }

}
