/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public class ObjCloneable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ObjCloneable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjCloneable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SCIPJNIJNI.delete_ObjCloneable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    SCIPJNIJNI.ObjCloneable_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    SCIPJNIJNI.ObjCloneable_change_ownership(this, swigCPtr, true);
  }

  public ObjCloneable clone(SWIGTYPE_p_SCIP scip) {
    long cPtr = (getClass() == ObjCloneable.class) ? SCIPJNIJNI.ObjCloneable_clone(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip)) : SCIPJNIJNI.ObjCloneable_cloneSwigExplicitObjCloneable(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip));
    return (cPtr == 0) ? null : new ObjCloneable(cPtr, false);
  }

  public long iscloneable() {
    return (getClass() == ObjCloneable.class) ? SCIPJNIJNI.ObjCloneable_iscloneable(swigCPtr, this) : SCIPJNIJNI.ObjCloneable_iscloneableSwigExplicitObjCloneable(swigCPtr, this);
  }

  public ObjCloneable() {
    this(SCIPJNIJNI.new_ObjCloneable(), true);
    SCIPJNIJNI.ObjCloneable_director_connect(this, swigCPtr, true, true);
  }

}
