/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public class ObjExprhdlr extends ObjCloneable {
  private transient long swigCPtr;

  protected ObjExprhdlr(long cPtr, boolean cMemoryOwn) {
    super(SCIPJNIJNI.ObjExprhdlr_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjExprhdlr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SCIPJNIJNI.delete_ObjExprhdlr(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    SCIPJNIJNI.ObjExprhdlr_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    SCIPJNIJNI.ObjExprhdlr_change_ownership(this, swigCPtr, true);
  }

  public ObjExprhdlr(SWIGTYPE_p_SCIP scip, String name, String desc, long precedence, long has_copydata, long has_freedata, long has_simplify, long has_compare, long has_print, long has_parse, long has_bwdiff, long has_fwdiff, long has_bwfwdiff, long has_inteval, long has_estimate, long has_initestimates, long has_reverseprop, long has_hash, long has_curvature, long has_monotonicity, long has_integrality, long has_getsymdata) {
    this(SCIPJNIJNI.new_ObjExprhdlr__SWIG_0(SWIGTYPE_p_SCIP.getCPtr(scip), name, desc, precedence, has_copydata, has_freedata, has_simplify, has_compare, has_print, has_parse, has_bwdiff, has_fwdiff, has_bwfwdiff, has_inteval, has_estimate, has_initestimates, has_reverseprop, has_hash, has_curvature, has_monotonicity, has_integrality, has_getsymdata), true);
    SCIPJNIJNI.ObjExprhdlr_director_connect(this, swigCPtr, true, true);
  }

  public ObjExprhdlr(ObjExprhdlr o) {
    this(SCIPJNIJNI.new_ObjExprhdlr__SWIG_1(ObjExprhdlr.getCPtr(o), o), true);
    SCIPJNIJNI.ObjExprhdlr_director_connect(this, swigCPtr, true, true);
  }

  public SCIP_Retcode scip_freehdlr(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_Exprhdlr exprhdlr, SWIGTYPE_p_p_SCIP_ExprhdlrData exprhdlrdata) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_freehdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Exprhdlr.getCPtr(exprhdlr), SWIGTYPE_p_p_SCIP_ExprhdlrData.getCPtr(exprhdlrdata)) : SCIPJNIJNI.ObjExprhdlr_scip_freehdlrSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Exprhdlr.getCPtr(exprhdlr), SWIGTYPE_p_p_SCIP_ExprhdlrData.getCPtr(exprhdlrdata)));
  }

  public SCIP_Retcode scip_eval(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SWIGTYPE_p_double val, SWIGTYPE_p_SCIP_SOL sol) {
    return SCIP_Retcode.swigToEnum(SCIPJNIJNI.ObjExprhdlr_scip_eval(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_double.getCPtr(val), SWIGTYPE_p_SCIP_SOL.getCPtr(sol)));
  }

  public SCIP_Retcode scip_copydata(SWIGTYPE_p_SCIP targetscip, SWIGTYPE_p_SCIP_Exprhdlr targetexprhdlr, SWIGTYPE_p_p_SCIP_ExprData targetexprdata, SWIGTYPE_p_SCIP sourcescip, SWIGTYPE_p_SCIP_EXPR sourceexpr) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_copydata(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(targetscip), SWIGTYPE_p_SCIP_Exprhdlr.getCPtr(targetexprhdlr), SWIGTYPE_p_p_SCIP_ExprData.getCPtr(targetexprdata), SWIGTYPE_p_SCIP.getCPtr(sourcescip), SWIGTYPE_p_SCIP_EXPR.getCPtr(sourceexpr)) : SCIPJNIJNI.ObjExprhdlr_scip_copydataSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(targetscip), SWIGTYPE_p_SCIP_Exprhdlr.getCPtr(targetexprhdlr), SWIGTYPE_p_p_SCIP_ExprData.getCPtr(targetexprdata), SWIGTYPE_p_SCIP.getCPtr(sourcescip), SWIGTYPE_p_SCIP_EXPR.getCPtr(sourceexpr)));
  }

  public SCIP_Retcode scip_freedata(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_freedata(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr)) : SCIPJNIJNI.ObjExprhdlr_scip_freedataSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr)));
  }

  public SCIP_Retcode scip_simplify(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SWIGTYPE_p_p_SCIP_EXPR simplifiedexpr, SWIGTYPE_p_SCIP_EXPR_OWNERCREATE ownercreate, SWIGTYPE_p_void ownercreatedata) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_simplify(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_p_SCIP_EXPR.getCPtr(simplifiedexpr), SWIGTYPE_p_SCIP_EXPR_OWNERCREATE.getCPtr(ownercreate), SWIGTYPE_p_void.getCPtr(ownercreatedata)) : SCIPJNIJNI.ObjExprhdlr_scip_simplifySwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_p_SCIP_EXPR.getCPtr(simplifiedexpr), SWIGTYPE_p_SCIP_EXPR_OWNERCREATE.getCPtr(ownercreate), SWIGTYPE_p_void.getCPtr(ownercreatedata)));
  }

  public int scip_compare(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr1, SWIGTYPE_p_SCIP_EXPR expr2) {
    return (getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_compare(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr1), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr2)) : SCIPJNIJNI.ObjExprhdlr_scip_compareSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr1), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr2));
  }

  public SCIP_Retcode scip_print(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, long stage, int currentchild, long parentprecedence, SWIGTYPE_p_FILE file) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_print(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), stage, currentchild, parentprecedence, SWIGTYPE_p_FILE.getCPtr(file)) : SCIPJNIJNI.ObjExprhdlr_scip_printSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), stage, currentchild, parentprecedence, SWIGTYPE_p_FILE.getCPtr(file)));
  }

  public SCIP_Retcode scip_parse(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_Exprhdlr exprhdlr, SWIGTYPE_p_char stringptr, SWIGTYPE_p_p_char endstring, SWIGTYPE_p_p_SCIP_EXPR expr, SWIGTYPE_p_unsigned_int success, SWIGTYPE_p_SCIP_EXPR_OWNERCREATE ownercreate, SWIGTYPE_p_void ownercreatedata) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_parse(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Exprhdlr.getCPtr(exprhdlr), SWIGTYPE_p_char.getCPtr(stringptr), SWIGTYPE_p_p_char.getCPtr(endstring), SWIGTYPE_p_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_unsigned_int.getCPtr(success), SWIGTYPE_p_SCIP_EXPR_OWNERCREATE.getCPtr(ownercreate), SWIGTYPE_p_void.getCPtr(ownercreatedata)) : SCIPJNIJNI.ObjExprhdlr_scip_parseSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Exprhdlr.getCPtr(exprhdlr), SWIGTYPE_p_char.getCPtr(stringptr), SWIGTYPE_p_p_char.getCPtr(endstring), SWIGTYPE_p_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_unsigned_int.getCPtr(success), SWIGTYPE_p_SCIP_EXPR_OWNERCREATE.getCPtr(ownercreate), SWIGTYPE_p_void.getCPtr(ownercreatedata)));
  }

  public SCIP_Retcode scip_bwdiff(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, int childidx, SWIGTYPE_p_double val) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_bwdiff(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), childidx, SWIGTYPE_p_double.getCPtr(val)) : SCIPJNIJNI.ObjExprhdlr_scip_bwdiffSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), childidx, SWIGTYPE_p_double.getCPtr(val)));
  }

  public SCIP_Retcode scip_fwdiff(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SWIGTYPE_p_double dot, SWIGTYPE_p_SCIP_SOL direction) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_fwdiff(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_double.getCPtr(dot), SWIGTYPE_p_SCIP_SOL.getCPtr(direction)) : SCIPJNIJNI.ObjExprhdlr_scip_fwdiffSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_double.getCPtr(dot), SWIGTYPE_p_SCIP_SOL.getCPtr(direction)));
  }

  public SCIP_Retcode scip_bwfwdiff(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, int childidx, SWIGTYPE_p_double bardot, SWIGTYPE_p_SCIP_SOL direction) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_bwfwdiff(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), childidx, SWIGTYPE_p_double.getCPtr(bardot), SWIGTYPE_p_SCIP_SOL.getCPtr(direction)) : SCIPJNIJNI.ObjExprhdlr_scip_bwfwdiffSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), childidx, SWIGTYPE_p_double.getCPtr(bardot), SWIGTYPE_p_SCIP_SOL.getCPtr(direction)));
  }

  public SCIP_Retcode scip_inteval(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SCIP_Interval interval, SWIGTYPE_p_SCIP_EXPR_INTEVALVAR intevalvar, SWIGTYPE_p_void intevalvardata) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_inteval(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SCIP_Interval.getCPtr(interval), interval, SWIGTYPE_p_SCIP_EXPR_INTEVALVAR.getCPtr(intevalvar), SWIGTYPE_p_void.getCPtr(intevalvardata)) : SCIPJNIJNI.ObjExprhdlr_scip_intevalSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SCIP_Interval.getCPtr(interval), interval, SWIGTYPE_p_SCIP_EXPR_INTEVALVAR.getCPtr(intevalvar), SWIGTYPE_p_void.getCPtr(intevalvardata)));
  }

  public SCIP_Retcode scip_estimate(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SCIP_Interval localbounds, SCIP_Interval globalbounds, SWIGTYPE_p_double refpoint, long overestimate, double targetvalue, SWIGTYPE_p_double coefs, SWIGTYPE_p_double constant, SWIGTYPE_p_unsigned_int islocal, SWIGTYPE_p_unsigned_int success, SWIGTYPE_p_unsigned_int branchcand) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_estimate(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SCIP_Interval.getCPtr(localbounds), localbounds, SCIP_Interval.getCPtr(globalbounds), globalbounds, SWIGTYPE_p_double.getCPtr(refpoint), overestimate, targetvalue, SWIGTYPE_p_double.getCPtr(coefs), SWIGTYPE_p_double.getCPtr(constant), SWIGTYPE_p_unsigned_int.getCPtr(islocal), SWIGTYPE_p_unsigned_int.getCPtr(success), SWIGTYPE_p_unsigned_int.getCPtr(branchcand)) : SCIPJNIJNI.ObjExprhdlr_scip_estimateSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SCIP_Interval.getCPtr(localbounds), localbounds, SCIP_Interval.getCPtr(globalbounds), globalbounds, SWIGTYPE_p_double.getCPtr(refpoint), overestimate, targetvalue, SWIGTYPE_p_double.getCPtr(coefs), SWIGTYPE_p_double.getCPtr(constant), SWIGTYPE_p_unsigned_int.getCPtr(islocal), SWIGTYPE_p_unsigned_int.getCPtr(success), SWIGTYPE_p_unsigned_int.getCPtr(branchcand)));
  }

  public SCIP_Retcode scip_initestimates(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SCIP_Interval bounds, long overestimate, SWIGTYPE_p_p_double coefs, SWIGTYPE_p_double constant, SWIGTYPE_p_int nreturned) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_initestimates(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SCIP_Interval.getCPtr(bounds), bounds, overestimate, SWIGTYPE_p_p_double.getCPtr(coefs), SWIGTYPE_p_double.getCPtr(constant), SWIGTYPE_p_int.getCPtr(nreturned)) : SCIPJNIJNI.ObjExprhdlr_scip_initestimatesSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SCIP_Interval.getCPtr(bounds), bounds, overestimate, SWIGTYPE_p_p_double.getCPtr(coefs), SWIGTYPE_p_double.getCPtr(constant), SWIGTYPE_p_int.getCPtr(nreturned)));
  }

  public SCIP_Retcode scip_reverseprop(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SCIP_Interval bounds, SCIP_Interval childrenbounds, SWIGTYPE_p_unsigned_int infeasible) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_reverseprop(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SCIP_Interval.getCPtr(bounds), bounds, SCIP_Interval.getCPtr(childrenbounds), childrenbounds, SWIGTYPE_p_unsigned_int.getCPtr(infeasible)) : SCIPJNIJNI.ObjExprhdlr_scip_reversepropSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SCIP_Interval.getCPtr(bounds), bounds, SCIP_Interval.getCPtr(childrenbounds), childrenbounds, SWIGTYPE_p_unsigned_int.getCPtr(infeasible)));
  }

  public SCIP_Retcode scip_hash(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SWIGTYPE_p_unsigned_int hashkey, SWIGTYPE_p_unsigned_int childrenhashes) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_hash(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_unsigned_int.getCPtr(hashkey), SWIGTYPE_p_unsigned_int.getCPtr(childrenhashes)) : SCIPJNIJNI.ObjExprhdlr_scip_hashSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_unsigned_int.getCPtr(hashkey), SWIGTYPE_p_unsigned_int.getCPtr(childrenhashes)));
  }

  public SCIP_Retcode scip_curvature(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SCIP_EXPRCURV exprcurvature, SWIGTYPE_p_unsigned_int success, SWIGTYPE_p_SCIP_EXPRCURV childcurv) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_curvature(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), exprcurvature.swigValue(), SWIGTYPE_p_unsigned_int.getCPtr(success), SWIGTYPE_p_SCIP_EXPRCURV.getCPtr(childcurv)) : SCIPJNIJNI.ObjExprhdlr_scip_curvatureSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), exprcurvature.swigValue(), SWIGTYPE_p_unsigned_int.getCPtr(success), SWIGTYPE_p_SCIP_EXPRCURV.getCPtr(childcurv)));
  }

  public SCIP_Retcode scip_monotonicity(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, int childidx, SWIGTYPE_p_SCIP_MONOTONE result) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_monotonicity(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), childidx, SWIGTYPE_p_SCIP_MONOTONE.getCPtr(result)) : SCIPJNIJNI.ObjExprhdlr_scip_monotonicitySwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), childidx, SWIGTYPE_p_SCIP_MONOTONE.getCPtr(result)));
  }

  public SCIP_Retcode scip_integrality(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SWIGTYPE_p_unsigned_int integrality) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_integrality(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_unsigned_int.getCPtr(integrality)) : SCIPJNIJNI.ObjExprhdlr_scip_integralitySwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_unsigned_int.getCPtr(integrality)));
  }

  public SCIP_Retcode scip_getsymdata(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_EXPR expr, SWIGTYPE_p_p_SYM_ExprData symdata) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjExprhdlr.class) ? SCIPJNIJNI.ObjExprhdlr_scip_getsymdata(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_p_SYM_ExprData.getCPtr(symdata)) : SCIPJNIJNI.ObjExprhdlr_scip_getsymdataSwigExplicitObjExprhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_EXPR.getCPtr(expr), SWIGTYPE_p_p_SYM_ExprData.getCPtr(symdata)));
  }

}
