/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public class ObjEventhdlr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ObjEventhdlr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjEventhdlr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ObjEventhdlr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SCIPJNIJNI.delete_ObjEventhdlr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    SCIPJNIJNI.ObjEventhdlr_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    SCIPJNIJNI.ObjEventhdlr_change_ownership(this, swigCPtr, true);
  }

  public void setScip_(SWIGTYPE_p_SCIP value) {
    SCIPJNIJNI.ObjEventhdlr_scip__set(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(value));
  }

  public SWIGTYPE_p_SCIP getScip_() {
    long cPtr = SCIPJNIJNI.ObjEventhdlr_scip__get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SCIP(cPtr, false);
  }

  public void setScip_name_(String value) {
    SCIPJNIJNI.ObjEventhdlr_scip_name__set(swigCPtr, this, value);
  }

  public String getScip_name_() {
    return SCIPJNIJNI.ObjEventhdlr_scip_name__get(swigCPtr, this);
  }

  public void setScip_desc_(String value) {
    SCIPJNIJNI.ObjEventhdlr_scip_desc__set(swigCPtr, this, value);
  }

  public String getScip_desc_() {
    return SCIPJNIJNI.ObjEventhdlr_scip_desc__get(swigCPtr, this);
  }

  @SuppressWarnings("this-escape")
  public ObjEventhdlr(SWIGTYPE_p_SCIP scip, String name, String desc) {
    this(SCIPJNIJNI.new_ObjEventhdlr(SWIGTYPE_p_SCIP.getCPtr(scip), name, desc), true);
    SCIPJNIJNI.ObjEventhdlr_director_connect(this, swigCPtr, true, true);
  }

  public SCIP_Retcode scip_free(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_Eventhdlr eventhdlr) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjEventhdlr.class) ? SCIPJNIJNI.ObjEventhdlr_scip_free(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr)) : SCIPJNIJNI.ObjEventhdlr_scip_freeSwigExplicitObjEventhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr)));
  }

  public SCIP_Retcode scip_init(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_Eventhdlr eventhdlr) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjEventhdlr.class) ? SCIPJNIJNI.ObjEventhdlr_scip_init(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr)) : SCIPJNIJNI.ObjEventhdlr_scip_initSwigExplicitObjEventhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr)));
  }

  public SCIP_Retcode scip_exit(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_Eventhdlr eventhdlr) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjEventhdlr.class) ? SCIPJNIJNI.ObjEventhdlr_scip_exit(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr)) : SCIPJNIJNI.ObjEventhdlr_scip_exitSwigExplicitObjEventhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr)));
  }

  public SCIP_Retcode scip_initsol(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_Eventhdlr eventhdlr) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjEventhdlr.class) ? SCIPJNIJNI.ObjEventhdlr_scip_initsol(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr)) : SCIPJNIJNI.ObjEventhdlr_scip_initsolSwigExplicitObjEventhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr)));
  }

  public SCIP_Retcode scip_exitsol(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_Eventhdlr eventhdlr) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjEventhdlr.class) ? SCIPJNIJNI.ObjEventhdlr_scip_exitsol(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr)) : SCIPJNIJNI.ObjEventhdlr_scip_exitsolSwigExplicitObjEventhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr)));
  }

  public SCIP_Retcode scip_delete(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_Eventhdlr eventhdlr, SWIGTYPE_p_p_SCIP_EventData eventdata) {
    return SCIP_Retcode.swigToEnum((getClass() == ObjEventhdlr.class) ? SCIPJNIJNI.ObjEventhdlr_scip_delete(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr), SWIGTYPE_p_p_SCIP_EventData.getCPtr(eventdata)) : SCIPJNIJNI.ObjEventhdlr_scip_deleteSwigExplicitObjEventhdlr(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr), SWIGTYPE_p_p_SCIP_EventData.getCPtr(eventdata)));
  }

  public SCIP_Retcode scip_exec(SWIGTYPE_p_SCIP scip, SWIGTYPE_p_SCIP_Eventhdlr eventhdlr, SWIGTYPE_p_SCIP_Event event, SWIGTYPE_p_SCIP_EventData eventdata) {
    return SCIP_Retcode.swigToEnum(SCIPJNIJNI.ObjEventhdlr_scip_exec(swigCPtr, this, SWIGTYPE_p_SCIP.getCPtr(scip), SWIGTYPE_p_SCIP_Eventhdlr.getCPtr(eventhdlr), SWIGTYPE_p_SCIP_Event.getCPtr(event), SWIGTYPE_p_SCIP_EventData.getCPtr(eventdata)));
  }

}
