/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public class SCIP_EventVarFixed {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SCIP_EventVarFixed(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SCIP_EventVarFixed obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SCIPJNIJNI.delete_SCIP_EventVarFixed(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVar(SWIGTYPE_p_SCIP_VAR value) {
    SCIPJNIJNI.SCIP_EventVarFixed_var_set(swigCPtr, this, SWIGTYPE_p_SCIP_VAR.getCPtr(value));
  }

  public SWIGTYPE_p_SCIP_VAR getVar() {
    long cPtr = SCIPJNIJNI.SCIP_EventVarFixed_var_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SCIP_VAR(cPtr, false);
  }

  public SCIP_EventVarFixed() {
    this(SCIPJNIJNI.new_SCIP_EventVarFixed(), true);
  }

}
