/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public final class SCIP_MONOTONE {
  public final static SCIP_MONOTONE SCIP_MONOTONE_UNKNOWN = new SCIP_MONOTONE("SCIP_MONOTONE_UNKNOWN", SCIPJNIJNI.SCIP_MONOTONE_UNKNOWN_get());
  public final static SCIP_MONOTONE SCIP_MONOTONE_INC = new SCIP_MONOTONE("SCIP_MONOTONE_INC", SCIPJNIJNI.SCIP_MONOTONE_INC_get());
  public final static SCIP_MONOTONE SCIP_MONOTONE_DEC = new SCIP_MONOTONE("SCIP_MONOTONE_DEC", SCIPJNIJNI.SCIP_MONOTONE_DEC_get());
  public final static SCIP_MONOTONE SCIP_MONOTONE_CONST = new SCIP_MONOTONE("SCIP_MONOTONE_CONST", SCIPJNIJNI.SCIP_MONOTONE_CONST_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SCIP_MONOTONE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SCIP_MONOTONE.class + " with value " + swigValue);
  }

  private SCIP_MONOTONE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SCIP_MONOTONE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SCIP_MONOTONE(String swigName, SCIP_MONOTONE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SCIP_MONOTONE[] swigValues = { SCIP_MONOTONE_UNKNOWN, SCIP_MONOTONE_INC, SCIP_MONOTONE_DEC, SCIP_MONOTONE_CONST };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

