/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public final class SCIP_Vartype {
  public final static SCIP_Vartype SCIP_VARTYPE_BINARY = new SCIP_Vartype("SCIP_VARTYPE_BINARY", SCIPJNIJNI.SCIP_VARTYPE_BINARY_get());
  public final static SCIP_Vartype SCIP_VARTYPE_INTEGER = new SCIP_Vartype("SCIP_VARTYPE_INTEGER", SCIPJNIJNI.SCIP_VARTYPE_INTEGER_get());
  public final static SCIP_Vartype SCIP_VARTYPE_IMPLINT = new SCIP_Vartype("SCIP_VARTYPE_IMPLINT", SCIPJNIJNI.SCIP_VARTYPE_IMPLINT_get());
  public final static SCIP_Vartype SCIP_VARTYPE_CONTINUOUS = new SCIP_Vartype("SCIP_VARTYPE_CONTINUOUS", SCIPJNIJNI.SCIP_VARTYPE_CONTINUOUS_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SCIP_Vartype swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SCIP_Vartype.class + " with value " + swigValue);
  }

  private SCIP_Vartype(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SCIP_Vartype(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SCIP_Vartype(String swigName, SCIP_Vartype swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SCIP_Vartype[] swigValues = { SCIP_VARTYPE_BINARY, SCIP_VARTYPE_INTEGER, SCIP_VARTYPE_IMPLINT, SCIP_VARTYPE_CONTINUOUS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

