/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public final class SCIP_OrbitopeType {
  public final static SCIP_OrbitopeType SCIP_ORBITOPETYPE_FULL = new SCIP_OrbitopeType("SCIP_ORBITOPETYPE_FULL", SCIPJNIJNI.SCIP_ORBITOPETYPE_FULL_get());
  public final static SCIP_OrbitopeType SCIP_ORBITOPETYPE_PARTITIONING = new SCIP_OrbitopeType("SCIP_ORBITOPETYPE_PARTITIONING", SCIPJNIJNI.SCIP_ORBITOPETYPE_PARTITIONING_get());
  public final static SCIP_OrbitopeType SCIP_ORBITOPETYPE_PACKING = new SCIP_OrbitopeType("SCIP_ORBITOPETYPE_PACKING", SCIPJNIJNI.SCIP_ORBITOPETYPE_PACKING_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SCIP_OrbitopeType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SCIP_OrbitopeType.class + " with value " + swigValue);
  }

  private SCIP_OrbitopeType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SCIP_OrbitopeType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SCIP_OrbitopeType(String swigName, SCIP_OrbitopeType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SCIP_OrbitopeType[] swigValues = { SCIP_ORBITOPETYPE_FULL, SCIP_ORBITOPETYPE_PARTITIONING, SCIP_ORBITOPETYPE_PACKING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

