/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public final class SCIP_Status {
  public final static SCIP_Status SCIP_STATUS_UNKNOWN = new SCIP_Status("SCIP_STATUS_UNKNOWN", SCIPJNIJNI.SCIP_STATUS_UNKNOWN_get());
  public final static SCIP_Status SCIP_STATUS_USERINTERRUPT = new SCIP_Status("SCIP_STATUS_USERINTERRUPT", SCIPJNIJNI.SCIP_STATUS_USERINTERRUPT_get());
  public final static SCIP_Status SCIP_STATUS_NODELIMIT = new SCIP_Status("SCIP_STATUS_NODELIMIT", SCIPJNIJNI.SCIP_STATUS_NODELIMIT_get());
  public final static SCIP_Status SCIP_STATUS_TOTALNODELIMIT = new SCIP_Status("SCIP_STATUS_TOTALNODELIMIT", SCIPJNIJNI.SCIP_STATUS_TOTALNODELIMIT_get());
  public final static SCIP_Status SCIP_STATUS_STALLNODELIMIT = new SCIP_Status("SCIP_STATUS_STALLNODELIMIT", SCIPJNIJNI.SCIP_STATUS_STALLNODELIMIT_get());
  public final static SCIP_Status SCIP_STATUS_TIMELIMIT = new SCIP_Status("SCIP_STATUS_TIMELIMIT", SCIPJNIJNI.SCIP_STATUS_TIMELIMIT_get());
  public final static SCIP_Status SCIP_STATUS_MEMLIMIT = new SCIP_Status("SCIP_STATUS_MEMLIMIT", SCIPJNIJNI.SCIP_STATUS_MEMLIMIT_get());
  public final static SCIP_Status SCIP_STATUS_GAPLIMIT = new SCIP_Status("SCIP_STATUS_GAPLIMIT", SCIPJNIJNI.SCIP_STATUS_GAPLIMIT_get());
  public final static SCIP_Status SCIP_STATUS_SOLLIMIT = new SCIP_Status("SCIP_STATUS_SOLLIMIT", SCIPJNIJNI.SCIP_STATUS_SOLLIMIT_get());
  public final static SCIP_Status SCIP_STATUS_BESTSOLLIMIT = new SCIP_Status("SCIP_STATUS_BESTSOLLIMIT", SCIPJNIJNI.SCIP_STATUS_BESTSOLLIMIT_get());
  public final static SCIP_Status SCIP_STATUS_RESTARTLIMIT = new SCIP_Status("SCIP_STATUS_RESTARTLIMIT", SCIPJNIJNI.SCIP_STATUS_RESTARTLIMIT_get());
  public final static SCIP_Status SCIP_STATUS_OPTIMAL = new SCIP_Status("SCIP_STATUS_OPTIMAL", SCIPJNIJNI.SCIP_STATUS_OPTIMAL_get());
  public final static SCIP_Status SCIP_STATUS_INFEASIBLE = new SCIP_Status("SCIP_STATUS_INFEASIBLE", SCIPJNIJNI.SCIP_STATUS_INFEASIBLE_get());
  public final static SCIP_Status SCIP_STATUS_UNBOUNDED = new SCIP_Status("SCIP_STATUS_UNBOUNDED", SCIPJNIJNI.SCIP_STATUS_UNBOUNDED_get());
  public final static SCIP_Status SCIP_STATUS_INFORUNBD = new SCIP_Status("SCIP_STATUS_INFORUNBD", SCIPJNIJNI.SCIP_STATUS_INFORUNBD_get());
  public final static SCIP_Status SCIP_STATUS_TERMINATE = new SCIP_Status("SCIP_STATUS_TERMINATE", SCIPJNIJNI.SCIP_STATUS_TERMINATE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SCIP_Status swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SCIP_Status.class + " with value " + swigValue);
  }

  private SCIP_Status(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SCIP_Status(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SCIP_Status(String swigName, SCIP_Status swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SCIP_Status[] swigValues = { SCIP_STATUS_UNKNOWN, SCIP_STATUS_USERINTERRUPT, SCIP_STATUS_NODELIMIT, SCIP_STATUS_TOTALNODELIMIT, SCIP_STATUS_STALLNODELIMIT, SCIP_STATUS_TIMELIMIT, SCIP_STATUS_MEMLIMIT, SCIP_STATUS_GAPLIMIT, SCIP_STATUS_SOLLIMIT, SCIP_STATUS_BESTSOLLIMIT, SCIP_STATUS_RESTARTLIMIT, SCIP_STATUS_OPTIMAL, SCIP_STATUS_INFEASIBLE, SCIP_STATUS_UNBOUNDED, SCIP_STATUS_INFORUNBD, SCIP_STATUS_TERMINATE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

