/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public final class SCIP_Objsense {
  public final static SCIP_Objsense SCIP_OBJSENSE_MAXIMIZE = new SCIP_Objsense("SCIP_OBJSENSE_MAXIMIZE", SCIPJNIJNI.SCIP_OBJSENSE_MAXIMIZE_get());
  public final static SCIP_Objsense SCIP_OBJSENSE_MINIMIZE = new SCIP_Objsense("SCIP_OBJSENSE_MINIMIZE", SCIPJNIJNI.SCIP_OBJSENSE_MINIMIZE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SCIP_Objsense swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SCIP_Objsense.class + " with value " + swigValue);
  }

  private SCIP_Objsense(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SCIP_Objsense(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SCIP_Objsense(String swigName, SCIP_Objsense swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SCIP_Objsense[] swigValues = { SCIP_OBJSENSE_MAXIMIZE, SCIP_OBJSENSE_MINIMIZE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

