/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public class SCIP_Event {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SCIP_Event(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SCIP_Event obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SCIPJNIJNI.delete_SCIP_Event(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEventtype(long value) {
    SCIPJNIJNI.SCIP_Event_eventtype_set(swigCPtr, this, value);
  }

  public long getEventtype() {
    return SCIPJNIJNI.SCIP_Event_eventtype_get(swigCPtr, this);
  }

  public SCIP_Event() {
    this(SCIPJNIJNI.new_SCIP_Event(), true);
  }

}
