/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public class SCIP_EventRowCoefChanged {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SCIP_EventRowCoefChanged(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SCIP_EventRowCoefChanged obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SCIPJNIJNI.delete_SCIP_EventRowCoefChanged(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRow(SWIGTYPE_p_SCIP_ROW value) {
    SCIPJNIJNI.SCIP_EventRowCoefChanged_row_set(swigCPtr, this, SWIGTYPE_p_SCIP_ROW.getCPtr(value));
  }

  public SWIGTYPE_p_SCIP_ROW getRow() {
    long cPtr = SCIPJNIJNI.SCIP_EventRowCoefChanged_row_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SCIP_ROW(cPtr, false);
  }

  public void setCol(SWIGTYPE_p_SCIP_COL value) {
    SCIPJNIJNI.SCIP_EventRowCoefChanged_col_set(swigCPtr, this, SWIGTYPE_p_SCIP_COL.getCPtr(value));
  }

  public SWIGTYPE_p_SCIP_COL getCol() {
    long cPtr = SCIPJNIJNI.SCIP_EventRowCoefChanged_col_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SCIP_COL(cPtr, false);
  }

  public void setOldval(double value) {
    SCIPJNIJNI.SCIP_EventRowCoefChanged_oldval_set(swigCPtr, this, value);
  }

  public double getOldval() {
    return SCIPJNIJNI.SCIP_EventRowCoefChanged_oldval_get(swigCPtr, this);
  }

  public void setNewval(double value) {
    SCIPJNIJNI.SCIP_EventRowCoefChanged_newval_set(swigCPtr, this, value);
  }

  public double getNewval() {
    return SCIPJNIJNI.SCIP_EventRowCoefChanged_newval_get(swigCPtr, this);
  }

  public SCIP_EventRowCoefChanged() {
    this(SCIPJNIJNI.new_SCIP_EventRowCoefChanged(), true);
  }

}
