/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public final class SCIP_EXPRCURV {
  public final static SCIP_EXPRCURV SCIP_EXPRCURV_UNKNOWN = new SCIP_EXPRCURV("SCIP_EXPRCURV_UNKNOWN", SCIPJNIJNI.SCIP_EXPRCURV_UNKNOWN_get());
  public final static SCIP_EXPRCURV SCIP_EXPRCURV_CONVEX = new SCIP_EXPRCURV("SCIP_EXPRCURV_CONVEX", SCIPJNIJNI.SCIP_EXPRCURV_CONVEX_get());
  public final static SCIP_EXPRCURV SCIP_EXPRCURV_CONCAVE = new SCIP_EXPRCURV("SCIP_EXPRCURV_CONCAVE", SCIPJNIJNI.SCIP_EXPRCURV_CONCAVE_get());
  public final static SCIP_EXPRCURV SCIP_EXPRCURV_LINEAR = new SCIP_EXPRCURV("SCIP_EXPRCURV_LINEAR", SCIPJNIJNI.SCIP_EXPRCURV_LINEAR_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SCIP_EXPRCURV swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SCIP_EXPRCURV.class + " with value " + swigValue);
  }

  private SCIP_EXPRCURV(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SCIP_EXPRCURV(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SCIP_EXPRCURV(String swigName, SCIP_EXPRCURV swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SCIP_EXPRCURV[] swigValues = { SCIP_EXPRCURV_UNKNOWN, SCIP_EXPRCURV_CONVEX, SCIP_EXPRCURV_CONCAVE, SCIP_EXPRCURV_LINEAR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

