/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public final class SCIP_Stage {
  public final static SCIP_Stage SCIP_STAGE_INIT = new SCIP_Stage("SCIP_STAGE_INIT", SCIPJNIJNI.SCIP_STAGE_INIT_get());
  public final static SCIP_Stage SCIP_STAGE_PROBLEM = new SCIP_Stage("SCIP_STAGE_PROBLEM", SCIPJNIJNI.SCIP_STAGE_PROBLEM_get());
  public final static SCIP_Stage SCIP_STAGE_TRANSFORMING = new SCIP_Stage("SCIP_STAGE_TRANSFORMING", SCIPJNIJNI.SCIP_STAGE_TRANSFORMING_get());
  public final static SCIP_Stage SCIP_STAGE_TRANSFORMED = new SCIP_Stage("SCIP_STAGE_TRANSFORMED", SCIPJNIJNI.SCIP_STAGE_TRANSFORMED_get());
  public final static SCIP_Stage SCIP_STAGE_INITPRESOLVE = new SCIP_Stage("SCIP_STAGE_INITPRESOLVE", SCIPJNIJNI.SCIP_STAGE_INITPRESOLVE_get());
  public final static SCIP_Stage SCIP_STAGE_PRESOLVING = new SCIP_Stage("SCIP_STAGE_PRESOLVING", SCIPJNIJNI.SCIP_STAGE_PRESOLVING_get());
  public final static SCIP_Stage SCIP_STAGE_EXITPRESOLVE = new SCIP_Stage("SCIP_STAGE_EXITPRESOLVE", SCIPJNIJNI.SCIP_STAGE_EXITPRESOLVE_get());
  public final static SCIP_Stage SCIP_STAGE_PRESOLVED = new SCIP_Stage("SCIP_STAGE_PRESOLVED", SCIPJNIJNI.SCIP_STAGE_PRESOLVED_get());
  public final static SCIP_Stage SCIP_STAGE_INITSOLVE = new SCIP_Stage("SCIP_STAGE_INITSOLVE", SCIPJNIJNI.SCIP_STAGE_INITSOLVE_get());
  public final static SCIP_Stage SCIP_STAGE_SOLVING = new SCIP_Stage("SCIP_STAGE_SOLVING", SCIPJNIJNI.SCIP_STAGE_SOLVING_get());
  public final static SCIP_Stage SCIP_STAGE_SOLVED = new SCIP_Stage("SCIP_STAGE_SOLVED", SCIPJNIJNI.SCIP_STAGE_SOLVED_get());
  public final static SCIP_Stage SCIP_STAGE_EXITSOLVE = new SCIP_Stage("SCIP_STAGE_EXITSOLVE", SCIPJNIJNI.SCIP_STAGE_EXITSOLVE_get());
  public final static SCIP_Stage SCIP_STAGE_FREETRANS = new SCIP_Stage("SCIP_STAGE_FREETRANS", SCIPJNIJNI.SCIP_STAGE_FREETRANS_get());
  public final static SCIP_Stage SCIP_STAGE_FREE = new SCIP_Stage("SCIP_STAGE_FREE", SCIPJNIJNI.SCIP_STAGE_FREE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SCIP_Stage swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SCIP_Stage.class + " with value " + swigValue);
  }

  private SCIP_Stage(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SCIP_Stage(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SCIP_Stage(String swigName, SCIP_Stage swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SCIP_Stage[] swigValues = { SCIP_STAGE_INIT, SCIP_STAGE_PROBLEM, SCIP_STAGE_TRANSFORMING, SCIP_STAGE_TRANSFORMED, SCIP_STAGE_INITPRESOLVE, SCIP_STAGE_PRESOLVING, SCIP_STAGE_EXITPRESOLVE, SCIP_STAGE_PRESOLVED, SCIP_STAGE_INITSOLVE, SCIP_STAGE_SOLVING, SCIP_STAGE_SOLVED, SCIP_STAGE_EXITSOLVE, SCIP_STAGE_FREETRANS, SCIP_STAGE_FREE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

