/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public final class SCIP_VerbLevel {
  public final static SCIP_VerbLevel SCIP_VERBLEVEL_NONE = new SCIP_VerbLevel("SCIP_VERBLEVEL_NONE", SCIPJNIJNI.SCIP_VERBLEVEL_NONE_get());
  public final static SCIP_VerbLevel SCIP_VERBLEVEL_DIALOG = new SCIP_VerbLevel("SCIP_VERBLEVEL_DIALOG", SCIPJNIJNI.SCIP_VERBLEVEL_DIALOG_get());
  public final static SCIP_VerbLevel SCIP_VERBLEVEL_MINIMAL = new SCIP_VerbLevel("SCIP_VERBLEVEL_MINIMAL", SCIPJNIJNI.SCIP_VERBLEVEL_MINIMAL_get());
  public final static SCIP_VerbLevel SCIP_VERBLEVEL_NORMAL = new SCIP_VerbLevel("SCIP_VERBLEVEL_NORMAL", SCIPJNIJNI.SCIP_VERBLEVEL_NORMAL_get());
  public final static SCIP_VerbLevel SCIP_VERBLEVEL_HIGH = new SCIP_VerbLevel("SCIP_VERBLEVEL_HIGH", SCIPJNIJNI.SCIP_VERBLEVEL_HIGH_get());
  public final static SCIP_VerbLevel SCIP_VERBLEVEL_FULL = new SCIP_VerbLevel("SCIP_VERBLEVEL_FULL", SCIPJNIJNI.SCIP_VERBLEVEL_FULL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SCIP_VerbLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SCIP_VerbLevel.class + " with value " + swigValue);
  }

  private SCIP_VerbLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SCIP_VerbLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SCIP_VerbLevel(String swigName, SCIP_VerbLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SCIP_VerbLevel[] swigValues = { SCIP_VERBLEVEL_NONE, SCIP_VERBLEVEL_DIALOG, SCIP_VERBLEVEL_MINIMAL, SCIP_VERBLEVEL_NORMAL, SCIP_VERBLEVEL_HIGH, SCIP_VERBLEVEL_FULL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

