/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public class SCIP_EventRowAddedSepa {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SCIP_EventRowAddedSepa(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SCIP_EventRowAddedSepa obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SCIPJNIJNI.delete_SCIP_EventRowAddedSepa(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRow(SWIGTYPE_p_SCIP_ROW value) {
    SCIPJNIJNI.SCIP_EventRowAddedSepa_row_set(swigCPtr, this, SWIGTYPE_p_SCIP_ROW.getCPtr(value));
  }

  public SWIGTYPE_p_SCIP_ROW getRow() {
    long cPtr = SCIPJNIJNI.SCIP_EventRowAddedSepa_row_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SCIP_ROW(cPtr, false);
  }

  public SCIP_EventRowAddedSepa() {
    this(SCIPJNIJNI.new_SCIP_EventRowAddedSepa(), true);
  }

}
