/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public final class SCIP_SideType {
  public final static SCIP_SideType SCIP_SIDETYPE_LEFT = new SCIP_SideType("SCIP_SIDETYPE_LEFT", SCIPJNIJNI.SCIP_SIDETYPE_LEFT_get());
  public final static SCIP_SideType SCIP_SIDETYPE_RIGHT = new SCIP_SideType("SCIP_SIDETYPE_RIGHT", SCIPJNIJNI.SCIP_SIDETYPE_RIGHT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SCIP_SideType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SCIP_SideType.class + " with value " + swigValue);
  }

  private SCIP_SideType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SCIP_SideType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SCIP_SideType(String swigName, SCIP_SideType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SCIP_SideType[] swigValues = { SCIP_SIDETYPE_LEFT, SCIP_SIDETYPE_RIGHT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

