/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public class SCIP_EventTypeChg {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SCIP_EventTypeChg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SCIP_EventTypeChg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SCIPJNIJNI.delete_SCIP_EventTypeChg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOldtype(SCIP_Vartype value) {
    SCIPJNIJNI.SCIP_EventTypeChg_oldtype_set(swigCPtr, this, value.swigValue());
  }

  public SCIP_Vartype getOldtype() {
    return SCIP_Vartype.swigToEnum(SCIPJNIJNI.SCIP_EventTypeChg_oldtype_get(swigCPtr, this));
  }

  public void setNewtype(SCIP_Vartype value) {
    SCIPJNIJNI.SCIP_EventTypeChg_newtype_set(swigCPtr, this, value.swigValue());
  }

  public SCIP_Vartype getNewtype() {
    return SCIP_Vartype.swigToEnum(SCIPJNIJNI.SCIP_EventTypeChg_newtype_get(swigCPtr, this));
  }

  public void setVar(SWIGTYPE_p_SCIP_VAR value) {
    SCIPJNIJNI.SCIP_EventTypeChg_var_set(swigCPtr, this, SWIGTYPE_p_SCIP_VAR.getCPtr(value));
  }

  public SWIGTYPE_p_SCIP_VAR getVar() {
    long cPtr = SCIPJNIJNI.SCIP_EventTypeChg_var_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SCIP_VAR(cPtr, false);
  }

  public SCIP_EventTypeChg() {
    this(SCIPJNIJNI.new_SCIP_EventTypeChg(), true);
  }

}
