/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public final class SCIP_BoundType {
  public final static SCIP_BoundType SCIP_BOUNDTYPE_LOWER = new SCIP_BoundType("SCIP_BOUNDTYPE_LOWER", SCIPJNIJNI.SCIP_BOUNDTYPE_LOWER_get());
  public final static SCIP_BoundType SCIP_BOUNDTYPE_UPPER = new SCIP_BoundType("SCIP_BOUNDTYPE_UPPER", SCIPJNIJNI.SCIP_BOUNDTYPE_UPPER_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SCIP_BoundType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SCIP_BoundType.class + " with value " + swigValue);
  }

  private SCIP_BoundType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SCIP_BoundType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SCIP_BoundType(String swigName, SCIP_BoundType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SCIP_BoundType[] swigValues = { SCIP_BOUNDTYPE_LOWER, SCIP_BOUNDTYPE_UPPER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

