/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jscip;

public class SYM_EXPRDATA {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SYM_EXPRDATA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SYM_EXPRDATA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SCIPJNIJNI.delete_SYM_EXPRDATA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConstants(SWIGTYPE_p_double value) {
    SCIPJNIJNI.SYM_EXPRDATA_constants_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getConstants() {
    long cPtr = SCIPJNIJNI.SYM_EXPRDATA_constants_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setNconstants(int value) {
    SCIPJNIJNI.SYM_EXPRDATA_nconstants_set(swigCPtr, this, value);
  }

  public int getNconstants() {
    return SCIPJNIJNI.SYM_EXPRDATA_nconstants_get(swigCPtr, this);
  }

  public void setCoefficients(SWIGTYPE_p_double value) {
    SCIPJNIJNI.SYM_EXPRDATA_coefficients_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getCoefficients() {
    long cPtr = SCIPJNIJNI.SYM_EXPRDATA_coefficients_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setNcoefficients(int value) {
    SCIPJNIJNI.SYM_EXPRDATA_ncoefficients_set(swigCPtr, this, value);
  }

  public int getNcoefficients() {
    return SCIPJNIJNI.SYM_EXPRDATA_ncoefficients_get(swigCPtr, this);
  }

  public void setChildren(SWIGTYPE_p_p_SCIP_EXPR value) {
    SCIPJNIJNI.SYM_EXPRDATA_children_set(swigCPtr, this, SWIGTYPE_p_p_SCIP_EXPR.getCPtr(value));
  }

  public SWIGTYPE_p_p_SCIP_EXPR getChildren() {
    long cPtr = SCIPJNIJNI.SYM_EXPRDATA_children_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_SCIP_EXPR(cPtr, false);
  }

  public SYM_EXPRDATA() {
    this(SCIPJNIJNI.new_SYM_EXPRDATA(), true);
  }

}
