/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_SCIPJNI_WRAP_H_
#define SWIG_SCIPJNI_WRAP_H_

class SwigDirector_ObjMessagehdlr : public scip::ObjMessagehdlr, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ObjMessagehdlr(JNIEnv *jenv, unsigned int bufferedoutput);
    virtual ~SwigDirector_ObjMessagehdlr();
    virtual void scip_error(SCIP_MESSAGEHDLR *messagehdlr, FILE *file, char const *msg);
    virtual void scip_warning(SCIP_MESSAGEHDLR *messagehdlr, FILE *file, char const *msg);
    virtual void scip_dialog(SCIP_MESSAGEHDLR *messagehdlr, FILE *file, char const *msg);
    virtual void scip_info(SCIP_MESSAGEHDLR *messagehdlr, FILE *file, char const *msg);
    virtual SCIP_RETCODE scip_free(SCIP_MESSAGEHDLR *messagehdlr);
public:
    bool swig_overrides(int n) {
      return (n < 5 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<5> swig_override;
};


#endif
